@baseUrl = http://localhost:3333

POST {{baseUrl}}/vehicles
Content-Type: application/json

{
  "placa": "BRA2E19",
  "chassi": "9BWZZZ377VT004251",
  "renavam": "12345678910",
  "modelo": "Civic",
  "marca": "Honda",
  "ano": 2022
}

####

GET {{baseUrl}}/vehicles?page=1&limit=39
Content-Type: application/json


###

DELETE {{baseUrl}}/vehicles/26
Content-Type: application/json



### 
PATCH  {{baseUrl}}/vehicles/25
Content-Type: application/json

{
  "placa": "BRA2E19",
  "chassi": "9BWZZZ377VT004251",
  "renavam": "12345678910",
  "modelo": "Corola 3423423",
  "marca": "Toyota",
  "ano": 2023
}

### 
GET {{baseUrl}}/vehicles/25
Content-Type: application/json

