version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env 
    volumes:
      - .:/app  
      - /app/node_modules 
    ports:
      - "3333:3333"
    command: sh -c "npx prisma migrate deploy && npm run start:dev"  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    ports:
      - "4200:4200"